stages:
- name: install
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm install
- name: deploy
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demandcluster/test:v1
      pushRemote: true
      registry: harbor.demandcluster.com
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
timeout: 60
notification: {}
