#!/bin/bash
cat <<EOF | docker run --interactive node bash > ./node_modules/@demandcluster/reaction-channel-manager/src/schemas/schemas.graphql
set -eu
npm install --silent --global get-graphql-schema >/dev/null
get-graphql-schema "http://10.42.0.216:4001"
EOF
